'use strict';
const DEFAULTS = Object.freeze({breakfast:['包子豆浆','煎饼果子','鸡蛋面','小笼包','肠粉','馄饨','粥配小菜','饭团','鸡蛋三明治','油条豆浆','拌粉','蒸饺'],lunch:['黄焖鸡米饭','番茄鸡蛋面','麻辣烫','牛肉粉','饺子','炒饭','宫保鸡丁盖饭','猪脚饭','螺蛳粉','鸡腿饭','凉皮肉夹馍','酸菜鱼饭'],dinner:['家常小炒','牛肉面','水饺','砂锅米线','麻辣香锅','馄饨','炒面','粥配小菜','烤肉拌饭','重庆小面','番茄鸡蛋盖饭','馒头配炖菜']});
const NAMES={breakfast:'早餐',lunch:'午餐',dinner:'晚餐'};
const KEY='maomaoyu-meals-v1';
const $=s=>document.querySelector(s);
const cloneDefaults=()=>Object.fromEntries(Object.entries(DEFAULTS).map(([k,v])=>[k,[...v]]));
let personal=cloneDefaults(),meal='lunch',source='public',busy=false,angle=0,currentResult=null,avoidRepeat=true;
const excluded={},rejected={},last={},rejectCounts={};
let saveFailed=false;
try{const stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored){for(const k of Object.keys(NAMES)){if(Array.isArray(stored.menus?.[k]))personal[k]=[...new Set(stored.menus[k].filter(x=>typeof x==='string'&&x.trim()&&x.length<=20).map(x=>x.trim()))].slice(0,40);}avoidRepeat=stored.avoidRepeat!==false;}}catch{saveFailed=true;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({menus:personal,avoidRepeat}));saveFailed=false;}catch{saveFailed=true;toast('浏览器暂时不能保存；本次修改仍可使用，请勿关闭页面。');}}
function key(){return source+':'+meal;}
function allFoods(){return source==='public'?[...DEFAULTS[meal]]:personal[meal];}
function setFor(obj){return obj[key()]||(obj[key()]=new Set());}
function eligible(){return allFoods().filter(x=>!setFor(excluded).has(x)&&!setFor(rejected).has(x));}
function candidates(){const a=eligible();return avoidRepeat&&a.length>1?a.filter(x=>x!==last[key()]):a;}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4200);}
const canvas=$('#wheel'),ctx=canvas.getContext('2d'),wood=new Image();wood.src='wood.webp';wood.onload=()=>draw();
function draw(){const list=eligible();const count=list.length||1;const step=Math.PI*2/count;const cx=500,cy=500,r=464;ctx.clearRect(0,0,1000,1000);ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);ctx.beginPath();ctx.arc(0,0,488,0,Math.PI*2);ctx.fillStyle='#795029';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#d7ae75';ctx.stroke();for(let i=0;i<count;i++){const a=-Math.PI/2-step/2+i*step;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,a+step);ctx.closePath();ctx.fillStyle=i%2?'#ddb880':'#edcf9b';ctx.fill();ctx.save();ctx.clip();if(wood.complete&&wood.naturalWidth){ctx.globalAlpha=.32;ctx.globalCompositeOperation='multiply';ctx.drawImage(wood,-r,-r,r*2,r*2);}ctx.restore();ctx.strokeStyle='#946a3e';ctx.lineWidth=2;ctx.stroke();if(list.length){ctx.save();ctx.rotate(-Math.PI/2+i*step);ctx.fillStyle='#48301c';const scale=Math.min(1.6,Math.max(1,420/(canvas.clientWidth||420)));const fontSize=Math.round((count>22?22:count>16?25:count>12?28:31)*scale);ctx.font=`600 ${fontSize}px "PingFang SC","Microsoft YaHei",sans-serif`;ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillText(list[i].length>8?list[i].slice(0,7)+'…':list[i],r-36,0,330);ctx.restore();}}ctx.beginPath();ctx.arc(0,0,r+6,0,Math.PI*2);ctx.lineWidth=13;ctx.strokeStyle='#b2834e';ctx.stroke();ctx.beginPath();ctx.arc(0,0,478,0,Math.PI*2);ctx.lineWidth=3;ctx.strokeStyle='#f3d59e';ctx.stroke();ctx.restore();if(!list.length){ctx.fillStyle='#60411e';ctx.font='28px sans-serif';ctx.textAlign='center';ctx.fillText('先选几道想吃的',500,315);}}
function render(){document.querySelectorAll('[data-meal]').forEach(b=>{b.classList.toggle('active',b.dataset.meal===meal);b.setAttribute('aria-pressed',String(b.dataset.meal===meal));b.disabled=busy;});document.querySelectorAll('[data-source]').forEach(b=>{b.classList.toggle('active',b.dataset.source===source);b.setAttribute('aria-pressed',String(b.dataset.source===source));b.disabled=busy;});$('#avoid-repeat').checked=avoidRepeat;$('#avoid-repeat').disabled=busy;$('#source-note').textContent=source==='public'?'院长准备的常见吃食，不想吃的取消勾选就好。':'你的口味你做主。菜单只保存在此浏览器中。';$('#edit-menu').textContent=source==='public'?'复制并编辑我的菜单':'编辑我的菜单';const foods=allFoods();const list=$('#food-list');list.replaceChildren();for(const name of foods){const label=document.createElement('label');label.className='food-option';const skip=setFor(rejected).has(name);const off=setFor(excluded).has(name);if(skip)label.classList.add('rejected');if(off)label.classList.add('off');const box=document.createElement('input');box.type='checkbox';box.checked=!off&&!skip;box.disabled=busy||skip;box.addEventListener('change',()=>{box.checked?setFor(excluded).delete(name):setFor(excluded).add(name);currentResult=null;render();});const text=document.createElement('span');text.textContent=name;label.append(box,text);list.append(label);}if(!foods.length){const p=document.createElement('p');p.className='empty';p.textContent='菜单还是空的，添加几道喜欢的食物吧。';list.append(p);}const n=eligible().length;$('#count').textContent=n+' 道可抽';$('#spin').disabled=busy||!n;$('#spin').innerHTML=busy?'好吃的正在转过来…':'转一转，开饭！<span aria-hidden="true">↻</span>';const skipped=setFor(rejected).size;$('#round-info').textContent=!n?(foods.length?'本轮没有可抽的了，重新开始或勾选几道吧。':'先添加食物，再转一转。'):busy?'稍等一下，马上开饭。':`本轮 ${n} 道候选${skipped?' · 已跳过 '+skipped+' 道':''}`;$('#reset-round').hidden=!skipped;['#select-all','#edit-menu','#reset-round'].forEach(s=>$(s).disabled=busy);draw();}
async function spin(){if(busy)throw new Error('转盘正在转动');const pool=candidates();if(!pool.length)throw new Error('没有可抽的食物');const drawList=eligible();const picked=pool[Math.floor(Math.random()*pool.length)];const index=drawList.indexOf(picked);const step=2*Math.PI/drawList.length;const base=angle;const desired=(( -index*step)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);const current=((base%(Math.PI*2))+Math.PI*2)%(Math.PI*2);const delta=((desired-current+Math.PI*2)%(Math.PI*2))+Math.PI*2*5;busy=true;currentResult=null;render();const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?100:3800;await new Promise(resolve=>{const start=performance.now();function frame(now){const t=Math.min((now-start)/duration,1);angle=base+delta*(1-Math.pow(1-t,4));draw();if(t<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});angle=((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2);last[key()]=picked;currentResult={name:picked,key:key(),meal};busy=false;render();$('#result-food').textContent=picked;$('#ticket-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}).format(new Date())+' · '+NAMES[meal];$('#result-title').textContent='今天就吃';$('#result-comment').textContent=(rejectCounts[key()]||0)>=5?'院长，你心里是不是已经有答案了？':'纠结到此为止，快乐从这顿开始。';$('#accept').hidden=false;$('#reject').hidden=false;$('#result-dialog').showModal();return {food:picked,meal:NAMES[meal]};}
$('#spin').onclick=()=>spin().catch(e=>toast(e.message));
document.querySelectorAll('[data-meal]').forEach(b=>b.onclick=()=>{if(busy)return;meal=b.dataset.meal;angle=0;currentResult=null;render();});
document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{if(busy)return;source=b.dataset.source;angle=0;currentResult=null;render();});
$('#avoid-repeat').onchange=e=>{avoidRepeat=e.target.checked;persist();};
$('#select-all').onclick=()=>{setFor(excluded).clear();render();};
$('#reset-round').onclick=()=>{setFor(rejected).clear();delete rejectCounts[key()];currentResult=null;render();toast('新的一轮，重新出发。');};
$('#close-result').onclick=()=>$('#result-dialog').close();
$('#accept').onclick=()=>{$('#result-dialog').close();$('#wheel-caption').textContent='这顿就吃：'+currentResult.name;toast('决定了！'+currentResult.name+'，开饭喵。');};
$('#reject').onclick=()=>{if(!currentResult||currentResult.key!==key())return;setFor(rejected).add(currentResult.name);rejectCounts[key()]=(rejectCounts[key()]||0)+1;currentResult=null;$('#result-dialog').close();render();if(eligible().length)spin().catch(e=>toast(e.message));else toast('已经全部排除啦，点「重新开始本轮」再选。');};
function editRows(){const list=$('#edit-list');list.replaceChildren();personal[meal].forEach((name,index)=>{const row=document.createElement('div');row.className='edit-row';const input=document.createElement('input');input.value=name;input.maxLength=20;input.setAttribute('aria-label','修改 '+name);input.onchange=()=>{const value=input.value.trim();if(!value){toast('食物名称不能为空。');input.value=name;return;}if(personal[meal].some((x,i)=>i!==index&&x===value)){toast('菜单里已经有这道啦。');input.value=name;return;}personal[meal][index]=value;setFor(excluded).delete(name);setFor(rejected).delete(name);persist();render();editRows();};const del=document.createElement('button');del.className='delete-food';del.textContent='删除';del.setAttribute('aria-label','删除 '+name);del.onclick=()=>{personal[meal].splice(index,1);setFor(excluded).delete(name);setFor(rejected).delete(name);persist();render();editRows();};row.append(input,del);list.append(row);});}
$('#edit-menu').onclick=()=>{if(source==='public'){const items=DEFAULTS[meal];personal[meal]=[...new Set([...personal[meal],...items])].slice(0,40);source='personal';persist();render();toast('已将院长菜单加入我的菜单，可以自由修改。');}$('#edit-title').textContent='我的'+NAMES[meal]+'菜单';editRows();$('#edit-dialog').showModal();};
$('#add-form').onsubmit=e=>{e.preventDefault();const name=$('#food-name').value.trim();if(!name){toast('写下食物或店名吧。');return;}if(personal[meal].length>=40){toast('最多放 40 道，先删掉几道再添加吧。');return;}if(personal[meal].includes(name)){toast('菜单里已经有这道啦。');return;}personal[meal].push(name);$('#food-name').value='';persist();render();editRows();$('#food-name').focus();};
$('#close-edit').onclick=$('#done-edit').onclick=()=>$('#edit-dialog').close();
render();if(saveFailed)toast('暂时无法读取已存菜单，本次先使用默认菜单。');
if(document.modelContext?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'get_meal_wheel',description:'读取当前餐次、菜单来源和可抽食物。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({meal,source,foods:eligible(),busy})});register({name:'spin_meal_wheel',description:'转动当前食物转盘并显示抽中结果，不代表用户接受该食物。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(input&&Object.keys(input).length)throw new Error('不接受额外参数');if($('#result-dialog').open||$('#edit-dialog').open)throw new Error('请先关闭当前弹窗');return spin();}});}

window.addEventListener('resize',()=>draw());
